const A=document.querySelector('#app'),T=document.querySelector('#toast');
const names={qafit:'القافط',malqoof:'الملقوف',musaaf:'المسعف',shaab:'الشعب',jasoos:'الجاسوس',abeet:'العبيط'};
const icons={qafit:'icon-qafit.svg',malqoof:'icon-malqoof.svg',musaaf:'icon-musaaf.svg',shaab:'icon-shaab.svg',jasoos:'icon-jasoos.svg',abeet:'icon-abeet.svg'};
const copy={qafit:'اقفط اللاعبين بعد المهمات، لكن لا تكشف نفسك.',malqoof:'تصل إليك معلومات تساعدك على مراقبة الجواسيس.',musaaf:'تستطيع إعادة لاعب معطّل مرة واحدة.',shaab:'أنجح المهمات وراقب التصرفات المشبوهة.',jasoos:'خرّب المهمة سرًا واكسب ثقة الشعب.',abeet:'جاسوس متنكر؛ يراك القافط كأنك من الشعب.'};
let mode='home',state=null,room='',token='',selected=[],timer,lastSnapshot='';
const toast=x=>{T.textContent=x;T.classList.add('show');setTimeout(()=>T.classList.remove('show'),3000)};
const api=async b=>{const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),j=await r.json();if(!r.ok)throw Error(j.error);return j};
async function create(){try{const j=await api({action:'create'});room=j.code;token=j.token;state=j.state;mode='game';startPoll();render()}catch(e){toast(e.message)}}
async function join(){room=document.querySelector('#code').value.toUpperCase();const name=document.querySelector('#name').value;try{const j=await api({action:'join',code:room,name});token=j.token;state=j.state;mode='game';startPoll();render()}catch(e){toast(e.message)}}
async function act(action,data={}){try{state=await api({action,code:room,token,...data});lastSnapshot=JSON.stringify(state);render()}catch(e){toast(e.message)}}
function startPoll(){clearInterval(timer);timer=setInterval(async()=>{try{const next=await api({action:'state',code:room,token}),snap=JSON.stringify(next);if(snap!==lastSnapshot){state=next;lastSnapshot=snap;render()}}catch{}},1300)}
function roleBadge(role,label=names[role]){return `<div class="identity"><img src="${icons[role]}" alt="${label}"><strong>${label}</strong></div>`}
function home(){return `<main class="landing"><div class="seal"><span>!</span></div><p class="eyebrow">لعبة خداع واستنتاج جماعية</p><h1>مهمة <em>سرية</em></h1><p class="intro">بينكم جواسيس. اختاروا فريق المهمة، راقبوا التصرفات، ولا تثقوا بأحد بسرعة.</p><div class="home-actions"><button onclick="create()">إنشاء لعبة</button><button class="ghost" onclick="mode='join';render()">الدخول برمز</button></div><small>من 4 إلى 10 لاعبين · كل لاعب من جواله</small></main>`}
function joinPage(){return `<main class="page-center"><section class="glass form scene-in"><button class="back" onclick="mode='home';render()">رجوع</button><div class="mini-seal">⌁</div><h2>الدخول إلى المهمة</h2><input id="name" placeholder="اسمك"><input id="code" maxlength="5" placeholder="رمز الغرفة"><button onclick="join()">دخول المهمة</button></section></main>`}
function pick(title,players,action){return `<div class="power"><b>${title}</b><div>${players.map(p=>`<button class="ghost" onclick="act('${action}',{target:'${p.id}'})">${p.name}</button>`).join('')}</div></div>`}
function phaseBox(me,leader,spy,current,size){
 if(state.phase==='lobby')return `<div class="waiting"><div class="radar"></div><p>شارك رمز الغرفة مع اللاعبين</p><small>تبدأ عند انضمام 4 لاعبين</small></div>${state.host?`<button ${state.players.length<4?'disabled':''} onclick="act('start')">ابدأ توزيع الشخصيات</button>`:''}`;
 if(state.phase==='select')return me?.id===leader?.id?`<p>اختر ${size} لاعبين للمهمة</p><div class="players">${state.players.map(p=>`<button class="${selected.includes(p.id)?'on':''}" onclick="toggle('${p.id}',${size})">${p.name}</button>`).join('')}</div><button onclick="act('select',{team:selected})" ${selected.length!==size?'disabled':''}>اعتماد فريق المهمة</button>`:`<div class="waiting"><div class="dots"><i></i><i></i><i></i></div><p>الريّس يختار فريق المهمة…</p></div>`;
 if(state.phase==='teamVote')return me&&current.vote===undefined?`<h3>هل توافق على فريق المهمة؟</h3><div class="vote"><button onclick="act('teamVote',{approve:true})">✓ أوافق</button><button class="danger" onclick="act('teamVote',{approve:false})">✕ أرفض</button></div>`:`<div class="waiting"><div class="dots"><i></i><i></i><i></i></div><p>بانتظار تصويت البقية…</p></div>`;
 if(state.phase==='missionVote')return me&&state.team.includes(me.id)&&!current.missionVote?`<div class="mission-choice"><h3>قرارك سري تمامًا</h3><button onclick="act('missionVote',{choice:'success'})">✓ إنجاح المهمة</button>${spy?`<button class="danger" onclick="act('missionVote',{choice:'fail'})">✕ تخريب المهمة</button>`:''}</div>`:`<div class="waiting"><div class="radar"></div><p>فريق المهمة يقرر سرًا…</p></div>`;
 if(state.phase==='result'){const failed=state.lastResult.fails;return `<div class="result ${failed?'failed':'passed'}"><div class="result-symbol">${failed?'✕':'✓'}</div><h2>${failed?'فشلت المهمة':'نجحت المهمة'}</h2><p>${failed?state.lastResult.fails+' تخريب سري':'دون أي تخريب'}</p></div>${me?.role==='qafit'&&!me.powerUsed&&!me.disabled?pick('اختر لاعبًا لقفطه',state.players.filter(p=>p.id!==me.id),'scan'):''}${spy&&!me.powerUsed&&failed?pick('عطّل لاعبًا سرًا',state.players.filter(p=>p.id!==me.id&&!p.disabled),'disable'):''}${me?.role==='musaaf'&&!me.powerUsed&&state.players.some(p=>p.disabled)?pick('اختر لاعبًا لإسعافه',state.players.filter(p=>p.disabled),'heal'):''}${state.host?`<button onclick="act('next')">المهمة التالية</button>`:''}`}
 if(state.phase==='assassination')return `<div class="result failed"><div class="result-symbol">⌖</div><h2>الفرصة الأخيرة</h2><p>على الجاسوس قفط القافط</p></div>${spy?pick('من هو القافط؟',state.players.filter(p=>p.id!==me.id),'assassinate'):'<div class="waiting"><p>الجواسيس يقررون…</p></div>'}`;
 if(state.phase==='finished')return `<div class="winner"><div class="winner-burst"></div><div class="result-symbol">★</div><small>انتهت المهمة السرية</small><h2>فاز ${state.winner}</h2><p>${state.message}</p></div>`;
 return '';
}
function game(){const me=state.me,leader=state.players[state.leaderIndex],spy=['jasoos','abeet'].includes(me?.role),size=state.players.length<=5?2:state.players.length<=8?3:4,current=state.players.find(p=>p.id===me?.id),box=phaseBox(me,leader,spy,current,size);return `<main class="wrap scene-in"><header class="topbar"><div><small>المهمة ${state.mission}</small><h3>${state.message}</h3></div><div class="room-code"><small>رمز الغرفة</small><b>${room}</b></div></header><div class="score"><span class="people">الشعب <b>${state.successes}</b>/3</span><span class="spies">الجواسيس <b>${state.failures}</b>/3</span></div>${me?.role?`<section class="glass role-card ${spy?'spy-role':''}"><small>شخصيتك السرية</small>${roleBadge(me.role)}<p>${copy[me.role]}</p>${me.spies?.length?`<div class="allies">معك: ${me.spies.join('، ')}</div>`:''}</section>`:''}${state.privateMessage?`<div class="secret-message"><span>معلومة سرية</span><p>${state.privateMessage}</p></div>`:''}<section class="glass mission-card"><div class="leader"><img src="icon-raees.svg" alt="الريّس"><div><small>الريّس الحالي</small><strong>${leader?.name||'بانتظار اللاعبين'}</strong></div></div><div class="phase-content">${box}</div></section><section class="glass roster"><h3>اللاعبون <span>${state.players.length}/10</span></h3>${state.players.map((p,i)=>`<div class="player-row ${p.disabled?'disabled-player':''}"><span>${p.name}</span>${i===state.leaderIndex?'<b>الريّس</b>':''}${state.team.includes(p.id)?'<em>فريق المهمة</em>':''}</div>`).join('')}</section></main>`}
function toggle(id,n){selected=selected.includes(id)?selected.filter(x=>x!==id):selected.length<n?[...selected,id]:selected;render()}
function render(){A.innerHTML=mode==='home'?home():mode==='join'?joinPage():game()}
render();
